export const titleMap = {
  url: "URL",
  canonical: "Canonical URL",
  title: "Title",
  description: "Description",
  keywords: "Keywords",
  h1s: "H1",
  ogType: "og:type",
  ogTitle: "og:title",
  ogDescription: "og:description",
  ogImage: "og:image",
  ogUrl: "og:url",
  ogSiteName: "og:site_name",
  twitterCard: "twitter:card",
  twitterTitle: "twitter:title",
  twitterDescription: "twitter:description",
  twitterImage: "twitter:image",
  robots: "Robots",
  googlebot: "Googlebot",
  hreflangs: "Hreflang",
  jsonLDs: "JSON-LD"
}
